/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/points/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get point balance
         * @description Retrieves point balance for a single Ethereum account.
         */
        get: {
            parameters: {
                query: {
                    campaignId: number;
                    account: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Point balance retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "account": "0x1234567890abcdef1234567890abcdef12345678",
                         *       "points": 1500
                         *     }
                         */
                        "application/json": {
                            /**
                             * @description Ethereum wallet address
                             * @example 0x1234567890abcdef1234567890abcdef12345678
                             */
                            account: string;
                            /**
                             * @description Total accumulated points
                             * @example 1500
                             */
                            points: number;
                        };
                    };
                };
                /** @description Invalid request (missing campaignId/account parameter or invalid address) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
                /** @description Campaign not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Get point balances (bulk)
         * @description Retrieves point balances for multiple Ethereum accounts (up to 100).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Campaign ID and accounts to query */
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "campaignId": 42,
                     *       "accounts": [
                     *         "0x1234567890abcdef1234567890abcdef12345678",
                     *         "0xabcdef1234567890abcdef1234567890abcdef12"
                     *       ]
                     *     }
                     */
                    "application/json": {
                        /**
                         * @description Campaign ID
                         * @example 42
                         */
                        campaignId: number;
                        /**
                         * @description Array of Ethereum addresses (1-100)
                         * @example [
                         *       "0x1234567890abcdef1234567890abcdef12345678",
                         *       "0xabcdef1234567890abcdef1234567890abcdef12"
                         *     ]
                         */
                        accounts: string[];
                    };
                };
            };
            responses: {
                /** @description Point balances retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "balances": [
                         *         {
                         *           "account": "0x1234567890abcdef1234567890abcdef12345678",
                         *           "points": 1500
                         *         },
                         *         {
                         *           "account": "0xabcdef1234567890abcdef1234567890abcdef12",
                         *           "points": 750
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": {
                            /** @description List of balances for requested accounts */
                            balances: {
                                /**
                                 * @description Ethereum wallet address
                                 * @example 0x1234567890abcdef1234567890abcdef12345678
                                 */
                                account: string;
                                /**
                                 * @description Total accumulated points
                                 * @example 1500
                                 */
                                points: number;
                            }[];
                        };
                    };
                };
                /** @description Invalid request (invalid campaignId, missing/empty accounts array, or invalid addresses) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
                /** @description Campaign not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/points/balance-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get point balances for multiple campaigns
         * @description Retrieves point balances for a single account across multiple campaigns (up to 50).
         *
         *     **Missing Campaign Handling:**
         *     Missing campaigns return 0 points with a warning entry. The call never fails due to missing campaigns - only for validation errors.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Campaign IDs and account to query */
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "campaignIds": [
                     *         1,
                     *         2,
                     *         3
                     *       ],
                     *       "account": "0x1234567890abcdef1234567890abcdef12345678"
                     *     }
                     */
                    "application/json": {
                        /**
                         * @description Array of campaign IDs (1-50)
                         * @example [
                         *       1,
                         *       2,
                         *       3
                         *     ]
                         */
                        campaignIds: number[];
                        /**
                         * @description Ethereum address to get balances for
                         * @example 0x1234567890abcdef1234567890abcdef12345678
                         */
                        account: string;
                    };
                };
            };
            responses: {
                /** @description Point balances retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "address": "0x1234567890abcdef1234567890abcdef12345678",
                         *       "campaignIds": [
                         *         1,
                         *         2,
                         *         3
                         *       ],
                         *       "points": [
                         *         100,
                         *         0,
                         *         300
                         *       ],
                         *       "warnings": [
                         *         {
                         *           "campaignId": 2,
                         *           "message": "Campaign not found"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": {
                            /**
                             * @description Lowercase Ethereum address
                             * @example 0x1234567890abcdef1234567890abcdef12345678
                             */
                            address: string;
                            /**
                             * @description Array of campaign IDs in request order
                             * @example [
                             *       1,
                             *       2,
                             *       3
                             *     ]
                             */
                            campaignIds: number[];
                            /**
                             * @description Array of point balances matching campaign order (0 for missing campaigns)
                             * @example [
                             *       100,
                             *       0,
                             *       300
                             *     ]
                             */
                            points: number[];
                            /**
                             * @description Warnings for campaigns that could not be found (still returns 0 points for those)
                             * @example [
                             *       {
                             *         "campaignId": 2,
                             *         "message": "Campaign not found"
                             *       }
                             *     ]
                             */
                            warnings?: {
                                /**
                                 * @description Campaign ID that triggered the warning
                                 * @example 2
                                 */
                                campaignId: number;
                                /**
                                 * @description Warning message
                                 * @example Campaign not found
                                 */
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Invalid request (invalid address, campaign ID format, or exceeds 50 campaigns limit) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/points/event-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get aggregated points for an event type
         * @description Retrieves the total points for a specific event type within a campaign.
         *
         *     **With account filter:** Returns the sum of points for that account and event type.
         *
         *     **Without account filter:** Returns the sum of points across all accounts for that event type.
         *
         *     This endpoint queries the raw point events and aggregates on-demand, unlike `/balance` which uses pre-aggregated balances.
         */
        get: {
            parameters: {
                query: {
                    campaignId: number;
                    eventName: string;
                    account?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event balance retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Event name that was queried
                             * @example swap
                             */
                            eventName: string;
                            /**
                             * @description Total aggregated points for this event type
                             * @example 1500
                             */
                            points: number;
                            /**
                             * @description Ethereum address (included when account filter was provided)
                             * @example 0x1234567890abcdef1234567890abcdef12345678
                             */
                            account?: string;
                        };
                    };
                };
                /** @description Invalid request (missing campaignId/eventName or invalid address) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
                /** @description Campaign not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/points/signed-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get signed point balance
         * @description Returns a signed point balance for on-chain verification. The signature follows the same format as Stack's getSignedPoints API.
         *
         *     **Signature Structure:**
         *     The message hash is computed as:
         *     ```
         *     keccak256(encodePacked([address, points, campaignId, timestamp]))
         *     ```
         *
         *     This can be verified on-chain using ECDSA recovery.
         */
        get: {
            parameters: {
                query: {
                    campaignId: number;
                    account: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Signed balance retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "address": "0x1234567890abcdef1234567890abcdef12345678",
                         *       "points": 1500,
                         *       "signatureTimestamp": 1704672000,
                         *       "signature": "0x8afc2c13c4ed315fcff3f93e4be66815ef259042c789f7e30be2a6160a5fc70f1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1c",
                         *       "signer": "0xBc2cfCd4c615Ff1d06f1d07b37E3652b15bd40A2"
                         *     }
                         */
                        "application/json": {
                            /**
                             * @description Lowercase Ethereum address
                             * @example 0x1234567890abcdef1234567890abcdef12345678
                             */
                            address: string;
                            /**
                             * @description Total accumulated points
                             * @example 1500
                             */
                            points: number;
                            /**
                             * @description Unix timestamp when the signature was generated
                             * @example 1704672000
                             */
                            signatureTimestamp: number;
                            /**
                             * @description EIP-191 signature of the message hash
                             * @example 0x8afc2c13c4ed315fcff3f93e4be66815ef259042c789f7e30be2a6160a5fc70f...
                             */
                            signature: string;
                            /**
                             * @description Address of the signer that produced the signature
                             * @example 0xBc2cfCd4c615Ff1d06f1d07b37E3652b15bd40A2
                             */
                            signer: string;
                        };
                    };
                };
                /** @description Invalid request (missing campaignId/account parameter or invalid address) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
                /** @description Campaign not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
                /** @description Internal server error (signing not available or other error) */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/points/signed-balance-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get batch signed point balances
         * @description Returns a single signature covering multiple campaigns for the same account. Enables batch on-chain claims.
         *
         *     **Signature Structure:**
         *     The message hash is computed as:
         *     ```
         *     keccak256(encodePacked([address, uint256[] points, uint256[] campaignIds, uint256 timestamp]))
         *     ```
         *
         *     This produces a single signature that covers all campaigns, allowing batch verification on-chain.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Campaign IDs and account to get signed balances for */
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "campaignIds": [
                     *         1,
                     *         2,
                     *         3
                     *       ],
                     *       "account": "0x1234567890abcdef1234567890abcdef12345678"
                     *     }
                     */
                    "application/json": {
                        /**
                         * @description Array of campaign IDs (1-50)
                         * @example [
                         *       1,
                         *       2,
                         *       3
                         *     ]
                         */
                        campaignIds: number[];
                        /**
                         * @description Ethereum address to get signed balances for
                         * @example 0x1234567890abcdef1234567890abcdef12345678
                         */
                        account: string;
                    };
                };
            };
            responses: {
                /** @description Batch signed balances retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "address": "0x1234567890abcdef1234567890abcdef12345678",
                         *       "campaignIds": [
                         *         1,
                         *         2,
                         *         3
                         *       ],
                         *       "points": [
                         *         100,
                         *         200,
                         *         300
                         *       ],
                         *       "signatureTimestamp": 1704672000,
                         *       "signature": "0x8afc2c13c4ed315fcff3f93e4be66815ef259042c789f7e30be2a6160a5fc70f1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1c",
                         *       "signer": "0xBc2cfCd4c615Ff1d06f1d07b37E3652b15bd40A2"
                         *     }
                         */
                        "application/json": {
                            /**
                             * @description Lowercase Ethereum address
                             * @example 0x1234567890abcdef1234567890abcdef12345678
                             */
                            address: string;
                            /**
                             * @description Array of campaign IDs in request order
                             * @example [
                             *       1,
                             *       2,
                             *       3
                             *     ]
                             */
                            campaignIds: number[];
                            /**
                             * @description Array of point balances matching campaign order
                             * @example [
                             *       100,
                             *       200,
                             *       300
                             *     ]
                             */
                            points: number[];
                            /**
                             * @description Unix timestamp when the signature was generated
                             * @example 1704672000
                             */
                            signatureTimestamp: number;
                            /**
                             * @description Single EIP-191 signature covering all campaigns
                             * @example 0x8afc2c13c4ed315fcff3f93e4be66815ef259042c789f7e30be2a6160a5fc70f...
                             */
                            signature: string;
                            /**
                             * @description Address of the signer that produced the signature
                             * @example 0xBc2cfCd4c615Ff1d06f1d07b37E3652b15bd40A2
                             */
                            signer: string;
                        };
                    };
                };
                /** @description Invalid request (invalid address, campaign ID format, or exceeds 50 campaigns limit) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
                /** @description One or more campaigns not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
                /** @description Internal server error (signing not available or other error) */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/points/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get point events
         * @description Retrieves point events with optional filtering by account, event name, and time range. Results are paginated and sorted by event time (newest first).
         */
        get: {
            parameters: {
                query: {
                    campaignId: number;
                    account?: string;
                    eventName?: string;
                    startTime?: string;
                    endTime?: string;
                    limit?: number;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Point events retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description List of point events */
                            events: {
                                /**
                                 * @description Event ID
                                 * @example 42
                                 */
                                id: number;
                                /**
                                 * @description Name of the event that awarded points
                                 * @example swap
                                 */
                                eventName: string;
                                /**
                                 * @description Ethereum address that received points
                                 * @example 0x1234567890abcdef1234567890abcdef12345678
                                 */
                                account: string;
                                /**
                                 * @description Points awarded (can be positive or negative)
                                 * @example 100
                                 */
                                points: number;
                                /**
                                 * @description Unique identifier for deduplication
                                 * @example tx-0xabc123
                                 */
                                uniqueId: string | null;
                                /**
                                 * @description ISO 8601 timestamp of when the event occurred
                                 * @example 2025-01-07T12:00:00.000Z
                                 */
                                createdAt: string;
                            }[];
                            /**
                             * Pagination
                             * @description Pagination metadata
                             */
                            pagination: {
                                /**
                                 * @description Current page number
                                 * @example 1
                                 */
                                page: number;
                                /**
                                 * @description Items per page
                                 * @example 50
                                 */
                                limit: number;
                                /**
                                 * @description Total number of documents
                                 * @example 150
                                 */
                                totalDocs: number;
                                /**
                                 * @description Total number of pages
                                 * @example 3
                                 */
                                totalPages: number;
                                /**
                                 * @description Whether there is a next page
                                 * @example true
                                 */
                                hasNextPage: boolean;
                                /**
                                 * @description Whether there is a previous page
                                 * @example false
                                 */
                                hasPrevPage: boolean;
                            };
                        };
                    };
                };
                /** @description Invalid request (missing/invalid campaignId, invalid pagination, address, or timestamp format) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
                /** @description Campaign not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/points/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push point events
         * @description Push one or more point events for processing. Events are processed asynchronously in the background.
         *
         *     **Campaign Validation (Strongly Recommended):**
         *
         *     Include the `campaign` field with the campaign ID to verify you're pushing to the correct campaign. If provided, it must match the API key's associated campaign or the request will be rejected with a 403 error.
         *
         *     **Request Formats:**
         *
         *     1. **Single Event** - Push a single event directly:
         *     ```json
         *     {
         *       "campaign": 42, // optional but strongly recommended
         *       "eventName": "swap",
         *       "account": "0x...",
         *       "points": 100,
         *       "uniqueId": "tx-0xabc" // optional
         *     }
         *     ```
         *
         *     2. **Batch with Shared eventName** - All events share the root eventName:
         *     ```json
         *     {
         *       "campaign": 42, // optional but strongly recommended
         *       "eventName": "swap",
         *       "uniqueId": "batch-123", // optional, applied to all
         *       "events": [
         *         { "account": "0x...", "points": 100 },
         *         { "account": "0x...", "points": 50 }
         *       ]
         *     }
         *     ```
         *
         *     3. **Batch with Per-Event eventNames** - Each event has its own eventName:
         *     ```json
         *     {
         *       "campaign": 42, // optional but strongly recommended
         *       "events": [
         *         { "eventName": "swap", "account": "0x...", "points": 100 },
         *         { "eventName": "stake", "account": "0x...", "points": 200 }
         *       ]
         *     }
         *     ```
         *
         *     **Deduplication:** If `uniqueId` is provided, duplicate events (same campaign + account + uniqueId) will be skipped.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Point event(s) to push */
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description Campaign ID (optional). If provided, must match the API key's associated campaign.
                         * @example 42
                         */
                        campaignId?: number;
                        /**
                         * @description **Deprecated**: Use 'campaignId' instead. Campaign ID (optional). If provided, must match the API key's associated campaign.
                         * @example 42
                         */
                        campaign?: number;
                        /**
                         * @description Name of the event (1-100 characters)
                         * @example swap
                         */
                        eventName: string;
                        /**
                         * @description Ethereum address to award points to
                         * @example 0x1234567890abcdef1234567890abcdef12345678
                         */
                        account: string;
                        /**
                         * @description Points to award (must be an integer)
                         * @example 100
                         */
                        points: number;
                        /**
                         * @description Unique identifier for deduplication (max 255 chars)
                         * @example tx-0xabc123
                         */
                        uniqueId?: string;
                    };
                };
            };
            responses: {
                /** @description Push request accepted for processing */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Status message
                             * @example Push request accepted for processing
                             */
                            message: string;
                            /**
                             * @description ID of the created push request for tracking
                             * @example 42
                             */
                            pushRequestId: number;
                            /**
                             * @description Number of events in the push request
                             * @example 5
                             */
                            eventCount: number;
                        };
                    };
                };
                /** @description Validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "message": "Validation failed",
                         *       "details": [
                         *         {
                         *           "path": "eventName",
                         *           "message": "String must contain at least 1 character(s)"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
                /** @description Unauthorized (missing or invalid API key) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
                /** @description Campaign mismatch (provided campaign ID does not match API key's campaign) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "message": "Provided campaign ID (99) does not match API key's campaign (42)"
                         *     }
                         */
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Validation failed
                             */
                            message: string;
                            /** @description Validation error details */
                            details?: {
                                path: string;
                                message: string;
                            }[];
                            /** @description List of invalid addresses */
                            invalid?: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * PointBalance
         * @description Point balance for a single account
         */
        PointBalance: {
            /**
             * @description Ethereum wallet address
             * @example 0x1234567890abcdef1234567890abcdef12345678
             */
            account: string;
            /**
             * @description Total accumulated points
             * @example 1500
             */
            points: number;
        };
        /**
         * PointBalancesResponse
         * @description Response containing multiple account balances
         */
        PointBalancesResponse: {
            /** @description List of balances for requested accounts */
            balances: {
                /**
                 * @description Ethereum wallet address
                 * @example 0x1234567890abcdef1234567890abcdef12345678
                 */
                account: string;
                /**
                 * @description Total accumulated points
                 * @example 1500
                 */
                points: number;
            }[];
        };
        /**
         * PointEvent
         * @description A single point event
         */
        PointEvent: {
            /**
             * @description Event ID
             * @example 42
             */
            id: number;
            /**
             * @description Name of the event that awarded points
             * @example swap
             */
            eventName: string;
            /**
             * @description Ethereum address that received points
             * @example 0x1234567890abcdef1234567890abcdef12345678
             */
            account: string;
            /**
             * @description Points awarded (can be positive or negative)
             * @example 100
             */
            points: number;
            /**
             * @description Unique identifier for deduplication
             * @example tx-0xabc123
             */
            uniqueId: string | null;
            /**
             * @description ISO 8601 timestamp of when the event occurred
             * @example 2025-01-07T12:00:00.000Z
             */
            createdAt: string;
        };
        /**
         * PointEventsResponse
         * @description Paginated list of point events
         */
        PointEventsResponse: {
            /** @description List of point events */
            events: {
                /**
                 * @description Event ID
                 * @example 42
                 */
                id: number;
                /**
                 * @description Name of the event that awarded points
                 * @example swap
                 */
                eventName: string;
                /**
                 * @description Ethereum address that received points
                 * @example 0x1234567890abcdef1234567890abcdef12345678
                 */
                account: string;
                /**
                 * @description Points awarded (can be positive or negative)
                 * @example 100
                 */
                points: number;
                /**
                 * @description Unique identifier for deduplication
                 * @example tx-0xabc123
                 */
                uniqueId: string | null;
                /**
                 * @description ISO 8601 timestamp of when the event occurred
                 * @example 2025-01-07T12:00:00.000Z
                 */
                createdAt: string;
            }[];
            /**
             * Pagination
             * @description Pagination metadata
             */
            pagination: {
                /**
                 * @description Current page number
                 * @example 1
                 */
                page: number;
                /**
                 * @description Items per page
                 * @example 50
                 */
                limit: number;
                /**
                 * @description Total number of documents
                 * @example 150
                 */
                totalDocs: number;
                /**
                 * @description Total number of pages
                 * @example 3
                 */
                totalPages: number;
                /**
                 * @description Whether there is a next page
                 * @example true
                 */
                hasNextPage: boolean;
                /**
                 * @description Whether there is a previous page
                 * @example false
                 */
                hasPrevPage: boolean;
            };
        };
        /**
         * Pagination
         * @description Pagination metadata
         */
        Pagination: {
            /**
             * @description Current page number
             * @example 1
             */
            page: number;
            /**
             * @description Items per page
             * @example 50
             */
            limit: number;
            /**
             * @description Total number of documents
             * @example 150
             */
            totalDocs: number;
            /**
             * @description Total number of pages
             * @example 3
             */
            totalPages: number;
            /**
             * @description Whether there is a next page
             * @example true
             */
            hasNextPage: boolean;
            /**
             * @description Whether there is a previous page
             * @example false
             */
            hasPrevPage: boolean;
        };
        /**
         * PushResponse
         * @description Response from push endpoint (202 Accepted)
         */
        PushResponse: {
            /**
             * @description Status message
             * @example Push request accepted for processing
             */
            message: string;
            /**
             * @description ID of the created push request for tracking
             * @example 42
             */
            pushRequestId: number;
            /**
             * @description Number of events in the push request
             * @example 5
             */
            eventCount: number;
        };
        /**
         * SignedBalanceResponse
         * @description Signed point balance for on-chain verification
         */
        SignedBalanceResponse: {
            /**
             * @description Lowercase Ethereum address
             * @example 0x1234567890abcdef1234567890abcdef12345678
             */
            address: string;
            /**
             * @description Total accumulated points
             * @example 1500
             */
            points: number;
            /**
             * @description Unix timestamp when the signature was generated
             * @example 1704672000
             */
            signatureTimestamp: number;
            /**
             * @description EIP-191 signature of the message hash
             * @example 0x8afc2c13c4ed315fcff3f93e4be66815ef259042c789f7e30be2a6160a5fc70f...
             */
            signature: string;
            /**
             * @description Address of the signer that produced the signature
             * @example 0xBc2cfCd4c615Ff1d06f1d07b37E3652b15bd40A2
             */
            signer: string;
        };
        /**
         * SignedBalanceBatchResponse
         * @description Batch signed point balance for on-chain batch claims
         */
        SignedBalanceBatchResponse: {
            /**
             * @description Lowercase Ethereum address
             * @example 0x1234567890abcdef1234567890abcdef12345678
             */
            address: string;
            /**
             * @description Array of campaign IDs in request order
             * @example [
             *       1,
             *       2,
             *       3
             *     ]
             */
            campaignIds: number[];
            /**
             * @description Array of point balances matching campaign order
             * @example [
             *       100,
             *       200,
             *       300
             *     ]
             */
            points: number[];
            /**
             * @description Unix timestamp when the signature was generated
             * @example 1704672000
             */
            signatureTimestamp: number;
            /**
             * @description Single EIP-191 signature covering all campaigns
             * @example 0x8afc2c13c4ed315fcff3f93e4be66815ef259042c789f7e30be2a6160a5fc70f...
             */
            signature: string;
            /**
             * @description Address of the signer that produced the signature
             * @example 0xBc2cfCd4c615Ff1d06f1d07b37E3652b15bd40A2
             */
            signer: string;
        };
        /**
         * BalanceBatchResponse
         * @description Batch point balances for multiple campaigns
         */
        BalanceBatchResponse: {
            /**
             * @description Lowercase Ethereum address
             * @example 0x1234567890abcdef1234567890abcdef12345678
             */
            address: string;
            /**
             * @description Array of campaign IDs in request order
             * @example [
             *       1,
             *       2,
             *       3
             *     ]
             */
            campaignIds: number[];
            /**
             * @description Array of point balances matching campaign order (0 for missing campaigns)
             * @example [
             *       100,
             *       0,
             *       300
             *     ]
             */
            points: number[];
            /**
             * @description Warnings for campaigns that could not be found (still returns 0 points for those)
             * @example [
             *       {
             *         "campaignId": 2,
             *         "message": "Campaign not found"
             *       }
             *     ]
             */
            warnings?: {
                /**
                 * @description Campaign ID that triggered the warning
                 * @example 2
                 */
                campaignId: number;
                /**
                 * @description Warning message
                 * @example Campaign not found
                 */
                message: string;
            }[];
        };
        /**
         * EventBalanceResponse
         * @description Aggregated point balance for a specific event type
         */
        EventBalanceResponse: {
            /**
             * @description Event name that was queried
             * @example swap
             */
            eventName: string;
            /**
             * @description Total aggregated points for this event type
             * @example 1500
             */
            points: number;
            /**
             * @description Ethereum address (included when account filter was provided)
             * @example 0x1234567890abcdef1234567890abcdef12345678
             */
            account?: string;
        };
        /**
         * ApiError
         * @description API error response
         */
        ApiError: {
            /**
             * @description Error message
             * @example Validation failed
             */
            message: string;
            /** @description Validation error details */
            details?: {
                path: string;
                message: string;
            }[];
            /** @description List of invalid addresses */
            invalid?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
